SELECT C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, (SUM(B.PRICE * A.SALES)) as TOTAL_SALES
FROM BOOK_SALES as A
JOIN BOOK as B ON B.BOOK_ID = A.BOOK_ID
JOIN AUTHOR as C ON C.AUTHOR_ID	= B.AUTHOR_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC