SELECT YEAR(O.SALES_DATE) AS YEAR, 
       MONTH(O.SALES_DATE) AS MONTH,
       COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(U.USER_ID) FROM USER_INFO AS U WHERE YEAR(U.JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS O
WHERE O.USER_ID IN (
    SELECT U.USER_ID
    FROM USER_INFO AS U
    WHERE YEAR(U.JOINED) = 2021
)
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
