SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(IFNULL(A.PRICE, 0) * B.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT as A
JOIN FOOD_ORDER as B ON B.PRODUCT_ID = A.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
