SELECT A.FLAVOR
FROM FIRST_HALF as A
INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) as JULY_TOTAL_ORDER 
    FROM JULY
    GROUP BY FLAVOR) as B
    ON A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + JULY_TOTAL_ORDER) DESC 
LIMIT 3;